### ISSUE TITLE
Angular 12/13 support

### ISSUE THREAD

**Issue by stas-lyu** [aditya-7/ng2-file-upload-fix-chunk-upload#1]
Please can you add support for angular cli 12/13

**Comment by Rlcolli4** [comment]
We have loved the implementation of this module in our angular projects, however we do need the support for Angular 13 as well. This is currently the error we get upon trying to run the application:

```
Error: Error on worker #3: Error: Compiled class declaration is not inside an IIFE: FileSelectDirective in C:/dev/rol/rol5/node_modules/ng2-chunk-file-upload/file-upload/file-select.directive.js
    at Esm5RenderingFormatter.addDefinitions (file:///C:/dev/rol/rol5/node_modules/@angular/compiler-cli/bundles/chunk-KWZNY2SK.js:4068:13)
    at file:///C:/dev/rol/rol5/node_modules/@angular/compiler-cli/bundles/chunk-KWZNY2SK.js:4314:27
    at Array.forEach (<anonymous>)
    at Renderer.renderFile (file:///C:/dev/rol/rol5/node_modules/@angular/compiler-cli/bundles/chunk-KWZNY2SK.js:4311:36)
    at file:///C:/dev/rol/rol5/node_modules/@angular/compiler-cli/bundles/chunk-KWZNY2SK.js:4299:36
    at Array.forEach (<anonymous>)
    at Renderer.renderProgram (file:///C:/dev/rol/rol5/node_modules/@angular/compiler-cli/bundles/chunk-KWZNY2SK.js:4296:46)
    at Transformer.transform (file:///C:/dev/rol/rol5/node_modules/@angular/compiler-cli/bundles/chunk-KWZNY2SK.js:4522:32)
    at file:///C:/dev/rol/rol5/node_modules/@angular/compiler-cli/bundles/chunk-KWZNY2SK.js:4602:34
    at Worker.<anonymous> (file:///C:/dev/rol/rol5/node_modules/@angular/compiler-cli/bundles/ngcc/src/execution/cluster/ngcc_cluster_worker.js:70:24)
    at ClusterMaster.onWorkerMessage (file:///C:/dev/rol/rol5/node_modules/@angular/compiler-cli/bundles/chunk-DJRTTRF3.js:1464:15)
    at file:///C:/dev/rol/rol5/node_modules/@angular/compiler-cli/bundles/chunk-DJRTTRF3.js:1374:71
    at EventEmitter.<anonymous> (file:///C:/dev/rol/rol5/node_modules/@angular/compiler-cli/bundles/chunk-DJRTTRF3.js:1532:15)
    at EventEmitter.emit (events.js:375:28)
    at Worker.<anonymous> (internal/cluster/master.js:182:13)
    at Worker.emit (events.js:375:28)
    at ChildProcess.<anonymous> (internal/cluster/worker.js:33:12)
    at ChildProcess.emit (events.js:375:28)
    at emit (internal/child_process.js:910:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```
The error locks up the starting commands and doesn't allow the application to run.

**Comment by Rlcolli4** [comment]
If this is also helpful I found this after cleaning up some more broken items in our cod:

```
- ng2-chunk-file-upload [module/esm5] (git+https://github.com/aditya-7/ng2-file-uploading-with-chunk.git)
Warning: Invalid constructor parameter decorator in C:/dev/rol/rol5/node_modules/ng2-chunk-file-upload/file-upload/file-select.directive.js:
 () => [
    { type: ElementRef, },
]
Warning: Invalid constructor parameter decorator in C:/dev/rol/rol5/node_modules/ng2-chunk-file-upload/file-upload/file-drop.directive.js:
 () => [
    { type: ElementRef, },
]
Warning: Invalid constructor parameter decorator in C:/dev/rol/rol5/node_modules/ng2-chunk-file-upload/file-upload/file-upload.module.js:
 () => []
```
I'm also taking a look locally to see if I can figure out what the issue is. If so I'll try to submit a pull request.
